### PR TITLE
Update protos for Qdrant 1.12, add new endpoints

### PR DESCRIPTION
**Pull request by JojiiOfficial**
Updates the protos and rust structures.

A few examples of the new APIs (also included in the rustdoc):

```rust
let matrix = client
    .search_matrix_offsets(
        SearchMatrixPointsBuilder::new("collection_name")
           .filter(Filter::must(vec![Condition::matches(
               "color",
               "red".to_string(),
           )]))
           .sample(1000)
           .limit(10),
    )
    .await?;

```
```rust
let ten_countries_with_most_poins_in_europe = client
    .facet(
         FacetCountsBuilder::new("world_data", "country")
             .limit(10)
             .filter(Filter::must(vec![Condition::matches(
                 "continent",
                 "Europe".to_string(),
             )])),
     )
     .await
     .unwrap();
```

### CODE REVIEW

**Comment by generall** [comment]
Could you please put examples into https://github.com/qdrant/rust-client/tree/master/tests/snippets  as well

**Review by timvisee — APPROVED** [review]

**Comment by JojiiOfficial** [comment]
Done!
Also added them here: https://github.com/qdrant/api-reference/pull/33

**Comment by generall** [comment]
@JojiiOfficial please don't change api-refernce just yet, it requires release

**Review by timvisee — APPROVED** [review]
Thanks for including the `on_disk` change.

**Review by timvisee — APPROVED** [review]

**Pull request merged**
