### PR TITLE
Move build script to test

### PR DESCRIPTION
**Pull request by llogiq**
I have used qdrant client in the past, and keeping a protoc compiler is a hassle not everyone wants or needs. With this change, protos will only be recompiled on test if the definitions change. Failing to do so will lead to a test failure in CI, but this way we don't need to run protoc on every build, and our Rust users won't need a protoc on the path to build their stuff with us.

### CODE REVIEW

**Review by coszio — APPROVED** [review]
👍 Code-wise looks good. I haven't played with this before, so another review would be helpful

**Comment by diptanu** [comment]
This is amazing! Just the other day I had to install the protoc compiler on a build machine.

**Comment by agourlay** [comment]
That's a very neat solution :+1: 

Could you please change the [Dependencies](https://github.com/qdrant/rust-client/blob/master/README.md#dependencies) section of the readme to reflect your change?

Basically protoc becomes a dev only requirement.

**Comment by timvisee** [comment]
I don't like the fact that it is a test now, but I get that this is done to add it under `dev-dependencies`.

Did you consider adding it as binary with the dependency behind a feature flag? Then we'd run it as `cargo run --bin protos --features protos`. We could add a `tools/generate_protos.sh` script to run it for us, like we've done in the [main](https://github.com/qdrant/qdrant) project to make it a bit nicer to run.

Maybe we could add a simple check like [this](https://github.com/qdrant/qdrant/blob/master/tests/openapi_consistency_check.sh) in CI to ensure the generated files match the proto definitions in the repository.

**Comment by llogiq** [comment]
I chose this way to keep our process simple. If we need to have another CI job, that needs to be maintained, and might get lost in a future change without us noticing. The tests will be run anyway. Also I usually run `cargo test` before I push (as we all should), so I don't have an additional step I could forget when updating protos.

Speaking of which. I just forgot to `cargo test` before pushing. Go me. 😁

**Comment by llogiq** [comment]
README updated.

**Review by generall — APPROVED** [review]

**Pull request merged**
