### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by agourlay**
Keeping things fresh.

### CODE REVIEW

**Review by timvisee — APPROVED** [review]
We probably need to regenerate to make CI green as well :+1:

**Comment by agourlay** [comment]
I need to:
- update the builders with the new `timeout` fields
- add tests to make sure we do not miss those again

**Comment by agourlay** [comment]
@timvisee I don't know why CI is still complaining about stubs, I have regenerated everything already :shrug:

**Comment by agourlay** [comment]
Got it green by adding a debug statement in the protos test to update the timestamp.

**Review by timvisee — APPROVED** [review]

**Pull request merged**
